AWSTemplateFormatVersion: '2010-09-09'

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DeploymentEnvironment:
    Type: String
    Description: 'The deployment environment:'
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  myServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/sample/
      Handler: sample.lambdahandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionName: 'samplefunction-dev'
      Description: A sample lambda function.
      Policies:
        - AWSLambdaBasicExecutionRole

      Tags:
        Env: dev

      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
            Name: !Sub 'sampleschedule'
            Schedule: rate(1 day)

  MyLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "SampleLogGroupLogs"
      RetentionInDays : 30
      Tags:
         - Key: 'Env'
           Value: 'Dev'