name: Deploy Lambda function

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.3
    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    - name: Switch to Terraform modules directory
      run: |
        working-directory: ./terraform
    - name: Initialize Terraform
      run: terraform init
    - name: Plan Terraform deployment
      run: terraform plan
    - name: Apply Terraform changes
      run: terraform apply -auto-approve