name: Deploy Lambda function

on:
  push:
    branches:
      - dev
env:
  TF_WORKING_DIR: terraform/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    - name: Initialize Terraform
      run: terraform init
    - name: Plan Terraform deployment
      run: terraform plan -no-color
    - name: Apply Terraform changes
      run: terraform apply -auto-approve