on:
  push:
    branches:
      - dev
jobs:
  build-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          role-to-assume: arn:aws:iam::231992682363:role/githuboidcrole
          aws-region: us-east-1