on:
  push:
    branches:
      - dev
    paths:
      - '!.github/workflows/**'

jobs:
  build-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::231992682363:role/githuboidcrole
          aws-region: us-east-1
      - name: Initialize Terraform
        run: terraform -chdir=./terraform/ init
      - name: Apply Terraform changes
        run: terraform -chdir=./terraform/ apply -auto-approve