on:
  push:
    branches:
      - dev
jobs:
  build-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::231992682363:role/githuboidcrole
          aws-region: us-east-1