on:
  pull_request:
    branches:
      - stage
jobs:
  Terraform-Plan:
    permissions:
      id-token: write
      contents: read
      actions: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Create Terraform Plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::231992682363:role/githuboidcrole
          aws-region: us-east-1
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./terraform/
          var_file: ./terraform/variables.tfvars
          label: integration
          
